# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: cardiac-mps-motion
author: Henrik Finsberg
logo: "logo.png"
copyright: "2022"
only_build_toc_files: true

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: cache
  timeout: 3000

# Information about where the book exists on the web
repository:
  url: https://github.com/ComputationalPhysiology/mps_motion # Online location of your book
  path_to_book: _sources # Optional path to your book, relative to the repository root
  branch: gh-pages # Which branch of the repository should be used when creating links (optional)

launch_buttons:
  notebook_interface: "jupyterlab" # The interface interactive links will activate ["classic", "jupyterlab"]
  binderhub_url: "https://mybinder.org"

html:
  use_issues_button: true
  use_repository_button: true

parse:
  myst_enable_extensions:
    - amsmath
    - dollarmath
    - linkify

sphinx:
  extra_extensions:
    - "sphinx.ext.autodoc"
    - "sphinx.ext.napoleon"
    - "sphinx.ext.viewcode"
