name: Github Pages

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-22.04
    container:
      image: ghcr.io/scientificcomputing/fenics-gmsh:2023-03-01
    env:
      # Directory that will be published on github pages
      PUBLISH_DIR: ./docs/_build/html

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: python3 -m pip install -e ".[docs]"

      - name: Build docs
        run: jupyter book build -W docs

      - name: Deploy
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{ env.PUBLISH_DIR }}
