# Simple workflow for deploying static content to GitHub Pages
name: Build docs

on:
  pull_request:
    branches:
      - "main"

  # This workflow can be executed inside another workfow file
  workflow_call:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    container: ghcr.io/scientificcomputing/fenics-gmsh:2023-08-16
    env:
      DEB_PYTHON_INSTALL_LAYOUT: deb_system
      PUBLISH_DIR: ./docs/_build/html

    steps:
      - name: Checkout
        uses: actions/checkout@v4


      - name: Install dependencies
        run: python3 -m pip install ".[docs]"

      - name: Cache notebooks
        id: cache-notebooks
        uses: actions/cache@v4
        with:
          path: _build
          key: cache_key_1 # Bump number manually when you want to clear the cache

      - name: Build docs
        run: jupyter book build -W --keep-going docs

      - name: Upload documentation as artifact
        uses: actions/upload-artifact@v4
        with:
          name: documentation
          path: ${{ env.PUBLISH_DIR }}
          if-no-files-found: error
