name: CI mpi

on: [push]

jobs:
  test:
    name: Run tests with in paralell
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/scientificcomputing/fenics-gmsh:2023-08-16

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install -e ".[test]"

      - name: Create a geometry in serial
        run: |
          cardiac-geometries create-biv-ellipsoid biv

      - name: Load and save mesh in paralell
        run: |
          mpirun -n 2 python3 tests/load_and_save.py biv/biv_ellipsoid.h5
